# Generated by Django 6.0.7 on 2026-07-08 10:15

import core.models
import django.contrib.postgres.constraints
import django.db.models.deletion
import uuid
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # btree_gist нужен для exclusion-констрейнта (защита от пересечения записей)
        BtreeGistExtension(),
        migrations.CreateModel(
            name='Bay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_id', models.BigIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('no_show_count', models.PositiveIntegerField(default=0, verbose_name='Неявок')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('service_type', models.CharField(choices=[('fixed', 'Фиксированная длительность'), ('flexible', 'Гибкая (осмотр, длительность оценочная)')], default='fixed', max_length=10)),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Длительность, мин')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServicePoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('timezone', models.CharField(default='Asia/Tashkent', max_length=64, verbose_name='Часовой пояс')),
                ('work_start', models.TimeField(verbose_name='Начало рабочего дня')),
                ('work_end', models.TimeField(verbose_name='Конец рабочего дня')),
                ('work_days', models.JSONField(default=list, verbose_name='Рабочие дни')),
                ('slot_buffer_minutes', models.PositiveIntegerField(default=10, verbose_name='Буфер между записями, мин')),
                ('reminder_hours_before', models.PositiveIntegerField(default=3, verbose_name='Напоминание за N часов')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Автосервис',
                'verbose_name_plural': 'Автосервисы',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField(verbose_name='Начало')),
                ('estimated_end_time', models.DateTimeField(verbose_name='Расчётный конец')),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Записан'), ('confirmed', 'Подтвердил'), ('in_progress', 'На посту'), ('done', 'Готово'), ('no_show', 'Не приехал'), ('cancelled', 'Отменён'), ('rescheduled', 'Перенесён')], db_index=True, default='scheduled', max_length=15)),
                ('source', models.CharField(choices=[('telegram', 'Telegram'), ('manual', 'Вручную (мастер)')], default='telegram', max_length=10)),
                ('note', models.TextField(blank=True, verbose_name='Комментарий')),
                ('bay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='core.bay')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='core.client')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='core.service')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('reminder', 'Напоминание'), ('shifted', 'Очередь сдвинулась'), ('cancelled', 'Запись отменена'), ('confirm_request', 'Просьба подтвердить')], max_length=20)),
                ('scheduled_for', models.DateTimeField(verbose_name='Когда отправить')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('sent', 'Отправлено'), ('failed', 'Ошибка')], default='pending', max_length=10)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.appointment')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='service_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.servicepoint'),
        ),
        migrations.AddField(
            model_name='bay',
            name='service_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bays', to='core.servicepoint'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['bay', 'start_time'], name='core_appoin_bay_id_a1e53a_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'start_time'], name='core_appoin_status_e35912_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ('scheduled', 'confirmed', 'in_progress'))), expressions=[(core.models.TsTzRange('start_time', 'estimated_end_time'), '&&'), ('bay', '=')], name='excl_overlapping_active_appts'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_end_time__gt', models.F('start_time'))), name='appt_end_after_start'),
        ),
    ]
