# Generated by Django 6.0.7 on 2026-07-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_servicepoint_address_servicepoint_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='car_details',
            field=models.CharField(blank=True, max_length=120, verbose_name='Автомобиль'),
        ),
    ]
