# Generated by Django 6.0.7 on 2026-07-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_appointment_car_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('uz', 'Ўзбекча (кирилл)')], default='ru', max_length=2, verbose_name='Язык'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_uz',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название (ўзб.)'),
        ),
    ]
