# Generated by Django 6.0.7 on 2026-07-08 13:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_notification_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceManager',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_id', models.BigIntegerField(db_index=True, verbose_name='Telegram ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Имя')),
                ('role', models.CharField(choices=[('owner', 'Владелец'), ('staff', 'Сотрудник')], default='owner', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('service_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='core.servicepoint')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
                'constraints': [models.UniqueConstraint(fields=('service_point', 'telegram_id'), name='uniq_manager_per_point')],
            },
        ),
    ]
