# Generated by Django 6.0.7 on 2026-07-10 14:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_servicemanager_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemanager',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/', verbose_name='Фото профиля'),
        ),
        migrations.AddField(
            model_name='servicemanager',
            name='bio',
            field=models.TextField(blank=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='servicemanager',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Стаж, лет'),
        ),
        migrations.AddField(
            model_name='servicepoint',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание (о сервисе)'),
        ),
        migrations.CreateModel(
            name='ManagerMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_type', models.CharField(choices=[('photo', 'Фото'), ('video', 'Видео (YouTube)')], max_length=5)),
                ('image', models.ImageField(blank=True, upload_to='manager_media/', verbose_name='Фото')),
                ('video_url', models.URLField(blank=True, verbose_name='Ссылка на YouTube')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='core.servicemanager')),
            ],
            options={
                'verbose_name': 'Медиа профиля',
                'verbose_name_plural': 'Медиа профилей',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
