# Generated by Django 6.0.7 on 2026-07-10 19:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_servicemanager_avatar_servicemanager_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLoginCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('telegram_id', models.BigIntegerField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Токены выданы')),
            ],
            options={
                'verbose_name': 'Код входа через Telegram',
                'verbose_name_plural': 'Коды входа через Telegram',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность работ, мин'),
        ),
        migrations.AddField(
            model_name='servicepoint',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=32, verbose_name='Телефон'),
        ),
    ]
