# Generated by Django 6.0.7 on 2026-07-11 11:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_telegramlogincode_appointment_duration_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePointMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_type', models.CharField(choices=[('photo', 'Фото'), ('video', 'Видео (YouTube)')], max_length=5)),
                ('image', models.ImageField(blank=True, upload_to='service_media/', verbose_name='Фото')),
                ('video_url', models.URLField(blank=True, verbose_name='Ссылка на YouTube')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('service_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='core.servicepoint')),
            ],
            options={
                'verbose_name': 'Медиа сервиса',
                'verbose_name_plural': 'Медиа сервисов',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
