# Generated by Django 6.0.7 on 2026-07-11 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_move_media_to_service_point'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManagerMedia',
        ),
    ]
