# Generated by Django 6.0.7 on 2026-07-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_client_user_alter_appointment_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemanager',
            name='bio_uz',
            field=models.TextField(blank=True, verbose_name='О себе (ўзб.)'),
        ),
        migrations.AddField(
            model_name='servicepoint',
            name='address_uz',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес (ўзб.)'),
        ),
        migrations.AddField(
            model_name='servicepoint',
            name='description_uz',
            field=models.TextField(blank=True, verbose_name='Описание (ўзб.)'),
        ),
    ]
