# Generated by Django 6.0.7 on 2026-07-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_servicemanager_bio_uz_servicepoint_address_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemanager',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('uz', 'Ўзбекча (кирилл)')], default='ru', max_length=2, verbose_name='Язык'),
        ),
    ]
