# Generated by Django 6.0.7 on 2026-07-11 18:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_servicemanager_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Выходной')),
                ('work_start', models.TimeField(blank=True, null=True, verbose_name='Начало')),
                ('work_end', models.TimeField(blank=True, null=True, verbose_name='Конец')),
                ('service_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='core.servicepoint')),
            ],
            options={
                'verbose_name': 'График дня',
                'verbose_name_plural': 'График по дням',
                'ordering': ['weekday'],
                'constraints': [models.UniqueConstraint(fields=('service_point', 'weekday'), name='uniq_hours_per_weekday')],
            },
        ),
    ]
