# Generated by Django 6.0.7 on 2026-07-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_workinghours'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepoint',
            name='min_lead_minutes',
            field=models.PositiveIntegerField(default=60, verbose_name='Не принимать записи онлайн ближе N минут'),
        ),
    ]
