# Generated by Django 6.0.7 on 2026-07-12 20:04

import core.models
import django.contrib.postgres.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_servicepoint_min_lead_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancel_reason',
            field=models.TextField(blank=True, verbose_name='Причина отмены'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('client', 'Клиент'), ('master', 'Мастер')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ('scheduled', 'confirmed', 'in_progress'))), expressions=[(core.models.TsTzRange('start_time', 'estimated_end_time'), '&&'), ('client', '=')], name='excl_overlapping_client_appts'),
        ),
    ]
