# Generated by Django 6.0.7 on 2026-07-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_appointment_cancel_reason_appointment_cancelled_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemanager',
            name='onboarding_seen',
            field=models.BooleanField(default=False),
        ),
    ]
