# Generated by Django 6.0.7 on 2026-07-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_servicemanager_onboarding_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='notification_channel',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('push', 'Push в приложении')], default='telegram', max_length=10, verbose_name='Канал уведомлений'),
        ),
        migrations.AddField(
            model_name='client',
            name='push_token',
            field=models.CharField(blank=True, max_length=200, verbose_name='Push-токен'),
        ),
        migrations.AddField(
            model_name='servicemanager',
            name='notification_channel',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('push', 'Push в приложении')], default='telegram', max_length=10, verbose_name='Канал уведомлений'),
        ),
        migrations.AddField(
            model_name='servicemanager',
            name='push_token',
            field=models.CharField(blank=True, max_length=200, verbose_name='Push-токен'),
        ),
    ]
